name: Java CI CD projeto test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-e-testes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Rodar build e testes com Maven
        run: mvn clean verify
